export const COMMIT_BORROWED_BOOK_DATA = 'commit_borrowed_book_data'
export const CHANGE_STEP = 'change_step'
export const COMMIT_TRUE_BORROWED_BOOK_DATA = 'commit_true_borrowed_book_data'
export const MODIFY_LIST_DATA = 'modify_list_data'
export const MODIFY_BORROW_RESULT_DATA = 'modify_borrow_result_data' 